name: Create release

on:
  push:
    branches: 
      - "master"
    tags:
      - '**' # includes x/y tags


permissions:
  contents: write

jobs:
  build:
    name: Build - ${{ matrix.platform.os-name }}
    env:
      CARGO_TERM_COLOR: always
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: sharpie-${{matrix.platform.target}}
          # Of course Windows has to be difficult
          path: |
            target/${{matrix.platform.target}}/release/sharpie
            target/${{matrix.platform.target}}/release/sharpie.exe

  release:
    needs: build
    name: Create release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      tag: ${{ github.ref_name }}
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v7
        with:
          path: artifacts

      - name: Rename files # because some of them have the same name
        run: |
          cd artifacts
          for f in */*; do
            mv $f ../$(echo $f | sed s@/sharpie@@)
          done

      - name: Create current release
        # Delete the 'current' tag, always succeeding then
        # (re)create the 'current' tag
        run: |
          gh release delete current \
            --repo="$GITHUB_REPOSITORY" \
            --yes --cleanup-tag || true
          gh release create current \
            --repo="$GITHUB_REPOSITORY" \
            --generate-notes

      - name: Upload files to current release
        run: |
          gh release upload current --clobber \
            --repo="$GITHUB_REPOSITORY" \
            sharpie-*

      - name: Create tagged release
        if: github.ref_type == 'tag'
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${tag#v}" \
            --generate-notes

      - name: Upload files to tagged release
        if: github.ref_type == 'tag'
        run: |
          gh release upload "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            sharpie-*


